### DISCUSSION TITLE
How to use asr_online with english?

### DISCUSSION THREAD

**Discussion by gnometsunami** [PaddlePaddle/PaddleSpeech#3328] [Q&A]
I want to test paddlespeech_server with asr_online to recognize english. But I am getting this error when using an english model. Do I have something configured wrong? Or are english models not supported?

error:
```
[2023-06-11 02:39:32,748] [   ERROR] - Can't find "transformer_librispeech-en-16k" in resource. Model name must be one of ['conformer_online_wenetspeech-zh-16k', 'conformer_u2pp_online_wenetspeech-zh-16k', 'conformer_online_multicn-zh-16k', 'conformer_online_aishell-zh-16k', 'deepspeech2online_wenetspeech-zh-16k', 'deepspeech2online_aishell-zh-16k']
```

config:
```
host: 0.0.0.0
port: 8091
protocol: 'websocket'
engine_list: ['asr_online']
asr_online:
    model_type: 'transformer_librispeech'
    am_model: # the pdmodel file of am static model [optional]
    am_params:  # the pdiparams file of am static model [optional]
    lang: 'en'
    sample_rate: 16000
    cfg_path: 
    decode_method: 
    num_decoding_left_chunks: -1
    force_yes: True
    device: 'cpu' # cpu or gpu:id
    decode_method: "attention_rescoring"
    continuous_decoding: True # enable continue decoding when endpoint detected
    am_predictor_conf:
        device: 'cpu' # set 'gpu:id' or 'cpu'
        switch_ir_optim: True
        glog_info: False  # True -> print glog
        summary: True  # False -> do not show predictor config
    chunk_buffer_conf:
        window_n: 7     # frame
        shift_n: 4      # frame
        window_ms: 25   # ms
        shift_ms: 10    # ms
        sample_rate: 16000
        sample_width: 2
```
