### ISSUE TITLE
The package must be rebuilt with conda-build > 2.0.

### ISSUE THREAD

**Issue by iamfoolberg** [PaddlePaddle/PaddleSpeech#1387]
Hi there, when i follow the install scripts:
---------------------------------------------------
```
Install the Conda

#download the miniconda
wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -P tools/
#install the miniconda
bash tools/Miniconda3-latest-Linux-x86_64.sh -b
#conda init
$HOME/miniconda3/bin/conda init
#use the "bash" command to make the conda environment works
bash
#create a conda virtual environment
conda create -y -p tools/venv python=3.7
...
```
---------------------------------------------------
the `conda create -y -p tools/venv python=3.7` complains:

PaddingError: Placeholder of length '33' too short in package /home/berg/PaddleSpeech/tools/venv/python.pdb.
The package must be rebuilt with conda-build > 2.0.

I'm working in the ubuntu-18.04.6, with CUDA and cuDNN installed.

It seems that the something is wrong with miniconda, or something i've missed.

**Comment by Jackwaterveg** [comment]
You can try updating conda-build by using:
 `conda update conda `
`conda update conda-build`

If it still does not work, you can use to create a virtual environment:
`conda create -n paddlespeech python=3.7`
`conda activate paddlespeech`

**Comment by Jackwaterveg** [comment]
I have use the ubuntu18.04 docker with CUDA and cuDNN installed to reproduce your probelm. However, I can make the conda virtual environment without problems. Maybe you need to make sure the conda is installed correctly and try using the scripts above to solve the problem.

**Comment by iamfoolberg** [comment]
`vim ~/.condarc`
#use the following lines.
```
channels:
  - defaults
show_channel_urls: true
channel_alias: https://mirrors.tuna.tsinghua.edu.cn/anaconda
default_channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/pro
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2
custom_channels:
  conda-forge: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  msys2: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  bioconda: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  menpo: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  pytorch: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  simpleitk: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
```

that works:)
