### ISSUE TITLE
asr server 录制空白声音post过去后，也会request回来一些文字

### ISSUE THREAD

**Issue by 0902081008** [PaddlePaddle/PaddleSpeech#3576]
```
asr_python:
    model: 'conformer_wenetspeech'
    lang: 'zh'
    sample_rate: 16000
    cfg_path: # [optional]
    ckpt_path: # [optional]
    decode_method: 'attention_rescoring'
    num_decoding_left_chunks: -1
    force_yes: True
    device:  # set 'gpu:id' or 'cpu'


################### speech task: asr; engine_type: inference #######################
asr_inference:
    # model_type choices=['deepspeech2offline_aishell']
    model_type: 'deepspeech2offline_aishell'
    am_model: # the pdmodel file of am static model [optional]
    am_params:  # the pdiparams file of am static model [optional]
    lang: 'zh'
    sample_rate: 16000
    cfg_path: 
    num_decoding_left_chunks: -1
    decode_method: 
    force_yes: True

    am_predictor_conf:
        device:  # set 'gpu:id' or 'cpu'
        switch_ir_optim: True
        glog_info: False  # True -> print glog
        summary: True  # False -> do not show predictor config
```

请问如何能做到，声音中没有人声的时候，可以返回空白，而不是随机的一些文字？
